env: cube

method: xot  

task:  
  data: data/cube/cube_test.csv  
  total_game_step: 4  
  task_start_index: 0  
  task_end_index: 1 
  
gpt:  
  backend: gpt-4
  temperature: 0.0  
  stop: None    
  
param:
  n_generate_sample: 1  
  n_evaluate_sample: None 
  n_select_sample: None 
  last_step: 0 
  
multi_solution: 0  
  
xot:  
  numMCTSSims: 10  
  multi_numMCTSSims: 10  
  multi_solution_exploration: 50 
  
  revised: 0  
  revise_times: 0  
  revise_total_game_step: 7 
  revise_numMCTSSims: 500 
  
model:  
  checkpoint: ./models/cube
  filename: best.pth.tar
  cpuct: 1