env: game24

method: tot

task:  
  data: data/game24/game24_test.csv  
  total_game_step: 3  
  task_start_index: 0  
  task_end_index: 1 
  
gpt:  
  backend: gpt-4
  temperature: 0.0  
  stop: None    
  
param:
  n_generate_sample: 1  
  n_evaluate_sample: 1 
  n_select_sample: 1 
  last_step: 0
  
multi_solution: 0  
  
